# First, define some functions

# setopt NOTIFY

DO_OUTPUT=0
output_msg()
{
	if [[ $DO_OUTPUT = 1 ]]; then
		echo $@
	fi
}

#-------------------
# Other files to include
#-------------------
dotfile-load()
{
	for file in ${=*}
	do
		if [ -f ~/$file ]; then
		    . ~/$file
			output_msg "Loaded file $file"
		fi
	done	
}

INCLUDE_DOT_FILES=".zshrc_mako .zsh_prompt .zsh_completion .bash_aliases .bash_path"
dotfile-load $INCLUDE_DOT_FILES
